import _ from 'lodash';
import { FontIcons } from '../../assets/icons';
import * as Screens from '../../screens';

export const MainRoutes = [
  {
    id: 'Login',
    title: 'Login',
    description: '',
    icon: FontIcons.login,
    screen: Screens.Login,
    children: [],
  },
  {
    id: 'Dashboard',
    title: 'Dashboard',
    icon: FontIcons.dashboard,
    screen: Screens.Dashboard,
    children: [],
  },
  {
    id: 'AccountMenu',
    title: 'Account',
    icon: FontIcons.login,
    screen: Screens.AccountSummary,
    children: [
      {
        id: 'AccountSummary',
        title: 'Account',
        description: 'Summary',
        screen: Screens.AccountSummary,
        children: [],
      },     
      {
        id: 'AccountPayment',
        title: 'Account',
        description: 'Payment',
        screen: Screens.AccountPayment,
        children: [],
      },   
    ],
  },
  {
    id: 'ViolationMenu',
    title: 'Violation',
    icon: FontIcons.article,
    screen: Screens.Violations,
    children: [
      {
        id: 'Violations',
        title: 'Violations',
        description: 'Overview',
        screen: Screens.Violations,
        children: [],
      },     
      {
        id: 'Violation',
        title: 'Violation Detail',
        description: 'Detail',
        screen: Screens.Violation,
        children: [],
      },   
      {
        id: 'ViolationMap',
        title: 'Map',
        description: 'Map',
        screen: Screens.ViolationMap,
        children: [],
      },   
    ],
  },
  {
    id: 'WorkOrderMenu',
    title: 'Work Orders',
    icon: FontIcons.mail,
    screen: Screens.WorkOrders,
    children: [
      {
        id: 'WorkOrders',
        title: 'Work Order',
        description: 'Overview',
        screen: Screens.WorkOrders,
        children: [],
      },     
      {
        id: 'WorkOrder',
        title: 'Work Order Detail',
        description: 'Detail',
        screen: Screens.WorkOrder,
        children: [],
      },       {
        id: 'WorkOrderMap',
        title: 'Map',
        description: 'Map',
        screen: Screens.WorkOrderMap,
        children: [],
      },   
    ],
  },
  {
    id: 'ArchitecturalMenu',
    title: 'Architecturals',
    icon: FontIcons.profile,
    screen: Screens.Architectural,
    children: [
      {
        id: 'Architecturals',
        title: 'Arc/Arb',
        description: 'Overview',
        screen: Screens.Architecturals,
        children: [],
      },     
      {
        id: 'Architectural',
        title: 'Arc/Arb Detail',
        description: 'Detail',
        screen: Screens.Architectural,
        children: [],
      }, 
      {
        id: 'ArchitecturalStatus',
        title: 'Status',
        description: 'Status',
        screen: Screens.ArchitecturalStatus,
        children: [],
      },     
    ],
  },
  {
    id: 'SocialMenu',
    title: 'Social',
    icon: FontIcons.profile,
    screen: Screens.SocialMenu,
    children: [
      {
        id: 'Profile',
        title: 'Profile',
        description: 'Detail',
        screen: Screens.Profile,
        children: [],
      },
      {
        id: 'ProfileV2',
        title: 'Profile V2',
        description: 'Detail',
        screen: Screens.ProfileV2,
        children: [],
      },
      {
        id: 'ProfileSettings',
        title: 'Profile Settings',
        screen: Screens.ProfileSettings,
        children: [],
      },
      {
        id: 'ProfileSettingsV2',
        title: 'Profile Settings V2',
        screen: Screens.ProfileSettingsV2,
        children: [],
      },
      {
        id: 'Notifications',
        title: 'Notifications',
        screen: Screens.Notifications,
        children: [],
      },
      {
        id: 'Contacts',
        title: 'Contacts',
        screen: Screens.Contacts,
        children: [],
      },
      {
        id: 'Feed',
        title: 'Feed',
        screen: Screens.Feed,
        children: [],
      },
    ],
  },
  {
    id: 'ArticlesMenu',
    title: 'Articles',
    icon: FontIcons.article,
    screen: Screens.ArticleMenu,
    children: [
      {
        id: 'Articles',
        title: 'Article List',
        screen: Screens.Articles,
        children: [],
      },
      {
        id: 'Blogposts',
        title: 'Blogposts',
        screen: Screens.Blogposts,
        children: [],
      },
      {
        id: 'Article',
        title: 'Article View',
        screen: Screens.Article,
        children: [],
      },
    ],
  },
  {
    id: 'MessagingMenu',
    title: 'Messaging',
    icon: FontIcons.mail,
    screen: Screens.MessagingMenu,
    children: [
      {
        id: 'Chat',
        title: 'Chat',
        screen: Screens.Chat,
        children: [],
      },
      {
        id: 'ChatList',
        title: 'Chat List',
        screen: Screens.ChatList,
        children: [],
      },
      {
        id: 'Comments',
        title: 'Comments',
        screen: Screens.Comments,
        children: [],
      },
    ],
  },
  {
    id: 'NavigationMenu',
    icon: FontIcons.navigation,
    title: 'Navigation',
    screen: Screens.NavigationMenu,
    children: [
      {
        id: 'GridV1',
        title: 'Grid Menu V1',
        screen: Screens.GridV1,
        children: [],
      },
      {
        id: 'GridV2',
        title: 'Grid Menu V2',
        screen: Screens.GridV2,
        children: [],
      },
      {
        id: 'Side',
        title: 'Side Menu',
        action: 'DrawerOpen',
        screen: Screens.SideMenu,
        children: [],
      },
    ],
  },
  {
    id: 'Documents',
    title: 'Documents',
    icon: FontIcons.other,
    screen: Screens.Documents,
    children: [],
  },
  {
    id: 'Settings',
    title: 'Settings',
    icon: FontIcons.other,
    screen: Screens.Settings,
    children: [],
  },
  {
    id: 'Themes',
    title: 'Themes',
    icon: FontIcons.theme,
    screen: Screens.Themes,
    children: [],
  },
];

export const MenuRoutes =  [
  {
    id: 'Dashboard',
    title: 'Dashboard',
    icon: FontIcons.dashboard,
    screen: Screens.Dashboard,
    children: [],
  },
  {
    id: 'AccountMenu',
    title: 'Account',
    icon: FontIcons.login,
    screen: Screens.AccountSummary,
    children: [],
  },
  {
    id: 'ViolationMenu',
    title: 'Violation',
    icon: FontIcons.article,
    screen: Screens.Violations,
    children: [],
  },
  {
    id: 'WorkOrderMenu',
    title: 'Work Orders',
    icon: FontIcons.mail,
    screen: Screens.WorkOrders,
    children: [],
  },
  {
    id: 'ArchitecturalMenu',
    title: 'Architecturals',
    icon: FontIcons.profile,
    screen: Screens.Architectural,
    children: [],
  },
  {
    id: 'Settings',
    title: 'Settings',
    icon: FontIcons.other,
    screen: Screens.Settings,
    children: [],
  },
];;
